---
- hosts: demo
  become: yes
  vars:
    package: httpd
  tasks:
    - name: remove "{{package}}" server
      action : yum name="{{package}}" state=present
    - name: start "{{package}}" server
      action : service name="{{package}}" state=restarted

