- hosts: demo
  user: ansible
  become: yes
  tasks:
    - name: installing apache server
      action: yum name=httpd state=present
    - name: restart the apache server
      action: service name=httpd state=restarted
    - name: copy index.html
      copy: 
        src: index.html
        dest: /var/www/html/
